name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build WinForms App
        run: |
          cd ASP.NET/WinFormsApp
          dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ASP.NET/WinFormsApp/bin/Release/net8.0-windows/win-x64/publish/HagViewer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
